// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import CareersIndexController from "./careers_index_controller"
application.register("careers-index", CareersIndexController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ReadMoreController from "./read_more_controller"
application.register("read-more", ReadMoreController)

import ShortlistController from "./shortlist_controller"
application.register("shortlist", ShortlistController)

import UserFormController from "./user_form_controller"
application.register("user-form", UserFormController)
